version: "3.9"
services:
    redis:
        image: 'redis:4-alpine'
        ports:
            - '6379:6379'
    flask: 
        build: ./server
        container_name: flask
        restart: always
        expose: 
            - 8080
        environment: 
            - REDIS_URL=redis
            - REDIS_PORT=6379
            - APP_NAME=MyServer
        depends_on:
            - redis
    nginx:
        build: ./nginx
        restart: always
        ports: 
            - "3000:3000"
    # web:
    #     build: ./client/react_app
    #     ports: 
    #         - 80:80
    #         - 5000:5000
    #     volumes:
    #         - ./client/react_app:/user/src/app
    #         #- ./client/react_app:/usr/share/nginx/html
    #     depends_on: 
    #         - server
    simple_worker:
        build: './simple_worker'
        privileged: true
        user: root
        depends_on:
            - redis
            - flask
